### ISSUE TITLE
bldy doesn't handle relative paths correctly

### ISSUE THREAD

**Issue by rminnich** [bldy/bldy#3]
cd sys/src/9/amd64
bldy //:inith

gets an error trying to open init9.c at the top level, instead of toplevel + sys/src/9/amd64/init9.c

**Comment by rminnich** [comment]
Full test:
git clone git@github.com:Harvey-OS/harvey
bash bootstrap.sh
unset GOROOT
unset GOPATH
unset HARVEY # be safe
build //:kernel # build sort of works
cd sys/src/9/amd64
bldy //:inith #fails

**Comment by sevki** [comment]
because `//` means root so either `:inith` or `//sys/src/9/amd64:inith` will work
