### ISSUE TITLE
bldy doesn't build a usable kernel for the util/GO* scripts

### ISSUE THREAD

**Issue by rminnich** [bldy/bldy#4]
It needs to build harvey* and leave them in sys/src/9/amd64 and does not.
git clone git@github.com:Harvey-OS/harvey
unset GOPATH
unset GOROOT
bash bootstrap.sh
bldy //:kernel
export HARVEY=`pwd`
bash util/GO9PCPU
ls -l sys/src/9/amd64/harvey # not there.
says it can't find harvey.32bit

Where is it putting everything?

**Comment by sevki** [comment]
this has been discussed
